### PR TITLE
Provide packaging via setuptools pyproject.toml with entrypoint and tests

### PR DESCRIPTION
**Pull request by Pythoniasm**
Help me fix workflows, if possible. Experienced in GitLab CI/CD but not GitHub workflows.

### CODE REVIEW

**Comment by xlucn** [comment]
Hi. Some of the changes really are helpful, such as adding a packaging file and standardizing the file structure. I don't have a lot of dev experiences in Python (or any other languages actually, I do not work as a developer lol), so those improvements are welcome.

Since I do believe the good practice of contributing to a project is to add one specific feature at a time, and not to add personalized changes. So some of the changes are more suitable to be in your own repo, if without discussions first. Such as changing the script name, requiring `requires-python = ">=3.10"`, or bumping the version to 1.0.0. Adding compiled binary is also weird.

(Or did you mistakenly created the PR in my repo, instead or yours?)

I would add the following. I can do these myself, but you could create separate PRs since you have already worked a lot on it:
- Add tests. Probably use the tests in github workflow
- Use a project file, either pyproject.toml or setup.py would be fine. And also adapt the project structure accordingly. But keep this change minimal like only adding a `main` function would be enough to create a entry point.
- More if you consider them appropriate.

Sorry to close this first. You can continue to discuss here, it's alright:)

**Comment by Pythoniasm** [comment]
Thanks for your feedback. I have adjusted the changes to minimal, with the following adaptations based on your feedback:

- Bumping version to the next feature release `0.3.0` instead of a major
- Changing back the entrypoint to `fio-cdm`
- Provide an entrypoint test according to the GitHub workflows
- I have left the required Python version to at least `3.9.13` since this is the Ubuntu 22.04 default currently. Anyone using Ubuntu from now on has at least that version after the latest `sudo apt upgrade`
- I will remove the binaries, yes, this is sketchy. I used the Windows binaries from the `fio` installer. However, we should not ship that. Changes incoming in short, however I will leave my fork-master with these binaries.

**Comment by xlucn** [comment]
I suggest creating **multiple** PRs, each containing changes about one topic.

>     * Bumping version to the next feature release `0.3.0` instead of a major

Probably leave that for me to decide

>     * I have left the required Python version to at least `3.9.13` since this is the Ubuntu 22.04 default currently. Anyone using Ubuntu from now on has at least that version after the latest `sudo apt upgrade`

It's about users who are using other version or distros, like older Ubuntu, Debian, etc. They have different versions of Python on their machine. That's the reason to keep the supported environment as wide as possible.

**Comment by xlucn** [comment]
Update: If you have your own intention of distributing this tool, e.g., for windows WSL users (I guess that's why you assume Ubuntu 22.04 to be default?), you can leave the tight requirement in your own version.

You are free to publish a "pycdm" with your preferences, I think the MIT license permits it.

**Pull request closed without merging**
